language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
install:
  - pip install PIL --allow-external PIL --allow-unverified PIL
script: cd tests && ./docbook.sh
sudo: false
branches:
  only:
    - master
    - develop
    - /release.*/
    - /.*travis/
notifications:
  email:
    on_success: change
    on_failure: change
